export const DOCKER_HUB_SEARCH_INPUT_CHANGED = 'DOCKER_HUB_SEARCH_INPUT_CHANGED';
export const BUILDER_NEXT_PAGE = 'BUILDER_NEXT_PAGE';
export const BUILDER_DISTRIBUTION_CHANGE = 'BUILDER_DISTRIBUTION_CHANGE';
